import SearchInput from "@/app/_components/SearchInput/SearchInput";
import "@/app/globals.css";
import CredentialsSidebar from "@/app/_components/CredentialsSidebar/CredentialsSidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({ children }) {
  return (
    <>
      <div className="flex w-full items-center gap-12 px-11">
        <h2 className="text-xl font-semibold">Add User</h2>
        <SearchInput width="352px" height="42px" />
      </div>
      <div className="mt-24 flex px-11">
        <CredentialsSidebar />
        <div className="w-full overflow-hidden pl-24">{children}</div>
      </div>
    </>
  );
}
