import MainLayout from "./_components/MainLayout/MainLayout";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
        spellCheck="false"
        cz-shortcut-listen="true"
      >
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
